linters-settings:
  gofumpt:
    extra-rules: true
  wsl:
    allow-assign-and-anything: false
    allow-assign-and-call: false

linters:
  disable-all: true
  enable:
    - gofmt
    - gofumpt
    - govet
    - staticcheck
    - wsl_v5
    - stylecheck
    - revive
    - sloglint
    - misspell